package io.github.freshmag.conversion.dsl

import io.github.freshmag.conversion.variationsOf
import io.github.freshmag.core.Element
import kotlin.collections.component1
import kotlin.collections.component2
import kotlin.collections.component3
import kotlin.collections.component4

/**
 * Visits the first element with any of the provided [names]. If [variations] is true, variations of the names are
 * also accepted. Returns the result of [block] if the element is present, otherwise null.
 */
fun <T> Visitor.acceptAnyOfOrNull(
    names: List<String>,
    variations: Boolean = true,
    block: (Element) -> T,
): T? {
    require(names.isNotEmpty()) { "At least one name must be provided" }
    val namesToSearch = if (variations) variationsOf(names.toList()) else names.toList()
    val match = e.findAny(namesToSearch)
    return match.visitOrNull(block)
}

/**
 * Visits the first element with any of the provided [names]. If [variations] is true, variations of the names are
 * also accepted. Returns the result of [block] if the element is present, otherwise throws an
 * [IllegalArgumentException]. The message of the exception is generated by the [message] function.
 */
@Throws(IllegalArgumentException::class)
fun <T> Visitor.acceptAnyOfOrThrow(
    names: List<String>,
    variations: Boolean = true,
    message: String = "Required element missing: ${names.joinToString()}",
    block: (Element) -> T,
): T =
    acceptAnyOfOrNull(names, variations, block)
        ?: throw IllegalArgumentException(message)

/**
 * Visits the first element with any of the provided [names]. If [variations] is true, variations of the names are
 * also accepted. Returns the result of [block] if the element is present, otherwise throws an
 * [IllegalArgumentException]. The message of the exception is generated by the [message] function.
 */
@Throws(IllegalArgumentException::class)
fun <T> Visitor.acceptAnyOfOrThrow(
    vararg names: String,
    variations: Boolean = true,
    message: String = "Missing at least one of the required elements: ${names.joinToString()}",
    block: (Element) -> T,
): T = acceptAnyOfOrThrow(names.toList(), variations, message, block)

/**
 * Visits the first element with any of the provided [names]. If [variations] is true, variations of the names are
 * also accepted. Returns the result of [block] if the element is present, otherwise null.
 */
fun <T> Visitor.acceptAnyOfOrNull(
    vararg names: String,
    variations: Boolean = true,
    block: (Element) -> T,
): T? = acceptAnyOfOrNull(names.toList(), variations, block)

/**
 * Visits all elements with the provided lists of [names]. Each list is treated as an alternative name for the same
 * element. If [variations] is true, variations of the names are also accepted. Finally, the [block] is called with
 * the list of elements. If any of the elements are missing, null is returned.
 */
fun <T> Visitor.acceptAllOfOrNull(
    names: List<List<String>>,
    variations: Boolean = false,
    block: (List<Element>) -> T,
): T? {
    require(names.isNotEmpty()) { "At least one name must be provided" }
    val namesToSearch = if (variations) names.map { variationsOf(it) } else names.toList()
    val matches = namesToSearch.mapNotNull { e.findAny(it) }
    return if (matches.size == names.size) {
        block(matches)
    } else {
        null
    }
}

/**
 * Visits all elements with the provided lists of [names]. Each inner list is treated as an alternative name for
 * the same element. If [variations] is true, variations of the names are also accepted.
 * Finally, the [block] is called with the list of elements. If any of the elements are missing, an
 * [IllegalArgumentException] is thrown.
 */
fun <T> Visitor.acceptAllOfOrThrow(
    names: List<List<String>>,
    variations: Boolean = false,
    message: String = "Missing at least one of the required elements: ${names.flatten().joinToString()}",
    block: (List<Element>) -> T,
): T =
    acceptAllOfOrNull(names, variations, block)
        ?: throw IllegalArgumentException(message)

/**
 * Visits all elements with the provided lists of [names]. Each inner list is treated as an alternative name for
 * the same element. If [variations] is true, variations of the names are also accepted.
 * Finally, the [block] is called with the list of elements. If any of the elements are missing, null is returned.
 */
fun <T> Visitor.acceptAllOfOrNull(
    vararg names: List<String>,
    variations: Boolean = false,
    block: (List<Element>) -> T,
): T? = acceptAllOfOrNull(names.toList(), variations, block)

/**
 * Visits all elements with the provided lists of [names]. Each list is treated as an alternative name for the same
 * element. If [variations] is true, variations of the names are also accepted.
 * Finally, the [block] is called with the list of elements. If any of the elements are missing, an
 * [IllegalArgumentException] is thrown.
 */
@Throws(IllegalArgumentException::class)
fun <T> Visitor.acceptAllOfOrThrow(
    vararg names: List<String>,
    variations: Boolean = false,
    message: String = "Missing at least one of the required elements: ${names.joinToString()}",
    block: (List<Element>) -> T,
): T = acceptAllOfOrThrow(names.toList(), variations, message, block)

/**
 * Visits all elements with the provided [names]. If [variations] is true, variations of the names are also
 * accepted. Finally, the [block] is called with the list of elements. If any of the elements are missing, null is
 * returned.
 */
fun <T> Visitor.acceptAllOfOrNull(
    vararg names: String,
    variations: Boolean = false,
    block: (List<Element>) -> T,
): T? = acceptAllOfOrNull(names.map { listOf(it) }, variations, block)

/**
 * Visits all elements with the provided [names]. If [variations] is true, variations of the names are also
 * accepted. Finally, the [block] is called with the list of elements. If any of the elements are missing, an
 * [IllegalArgumentException] is thrown.
 *
 * Note: variations are not considered by default.
 */
@Throws(IllegalArgumentException::class)
fun <T> Visitor.acceptAllOfOrThrow(
    vararg names: String,
    variations: Boolean = false,
    message: String = "Missing at least one of the required elements: ${names.joinToString()}",
    block: (List<Element>) -> T,
): T =
    acceptAllOfOrThrow(
        names.map { listOf(it) },
        variations = variations,
        message = message,
        block = block,
    )

/**
 * Visits the element with the provided [name]. Returns the result of [block] if the element is present, otherwise
 * null.
 */
fun <T> Visitor.acceptOrNull(
    name: String,
    variations: Boolean = false,
    block: (Element) -> T,
): T? =
    (if (variations) e.findAny(variationsOf(name)) else e.find(name))
        .visitOrNull(block)

/**
 * Visits the element with the provided [name]. Throws an [IllegalArgumentException] with [message] if the element
 * is missing.
 */
@Throws(IllegalArgumentException::class)
fun <T> Visitor.accept(
    name: String,
    variations: Boolean = false,
    message: String = "Required element missing: $name",
    block: (Element) -> T,
): T =
    acceptOrNull(name, variations, block)
        ?: throw IllegalArgumentException(message)

/**
 * Visits the elements with the provided [name1] and [name2]. If [variations] is true, variations of the names are
 * also accepted. Returns the result of [block] if both elements are present, otherwise null.
 */
fun <T> Visitor.acceptOrNull(
    name1: String,
    name2: String,
    variations: Boolean = false,
    block: (Element, Element) -> T,
): T? =
    acceptAllOfOrNull(name1, name2, variations = variations) { list ->
        val (elem1, elem2) = list
        block(elem1, elem2)
    }

/**
 * Visits the elements with the provided [name1] and [name2]. If [variations] is true, variations of the names are
 * also accepted. If at least one of the elements is missing, an [IllegalArgumentException] is thrown with [message].
 */
fun <T> Visitor.accept(
    name1: String,
    name2: String,
    variations: Boolean = false,
    message: String = "Missing at least one of the required elements: $name1, $name2",
    block: (Element, Element) -> T,
): T =
    acceptAllOfOrThrow(name1, name2, variations = variations, message = message) { list ->
        val (elem1, elem2) = list
        block(elem1, elem2)
    }

/**
 * Visits the elements with the provided [names1] and [names2], each one treated as alternative names of each
 * element. If [variations] is true, variations of the names are also accepted. Returns the result of [block] if
 * both elements are present, otherwise null.
 */
fun <T> Visitor.acceptAnyOfOrNull(
    names1: List<String>,
    names2: List<String>,
    variations: Boolean = false,
    block: (Element, Element) -> T,
): T? =
    acceptAllOfOrNull(names1, names2, variations = variations) { list ->
        val (elem1, elem2) = list
        block(elem1, elem2)
    }

/**
 * Visits the elements with the provided [names1] and [names2], each one treated as alternative names of each
 * element. If [variations] is true, variations of the names are also accepted. If at least one of the elements is
 * missing, an [IllegalArgumentException] is thrown with [message].
 */
fun <T> Visitor.acceptAnyOfOrThrow(
    names1: List<String>,
    names2: List<String>,
    variations: Boolean = false,
    message: String =
        "Missing at least one of the required elements: ${names1.joinToString()}, " +
            names2.joinToString(),
    block: (Element, Element) -> T,
): T =
    acceptAllOfOrThrow(names1, names2, variations = variations, message = message) { (elem1, elem2) ->
        block(elem1, elem2)
    }

/**
 * Visits the elements with the provided [name1], [name2], and [name3]. If [variations] is true, variations of the
 * names are also accepted. Returns the result of [block] if all elements are present, otherwise null.
 */
fun <T> Visitor.acceptOrNull(
    name1: String,
    name2: String,
    name3: String,
    variations: Boolean = false,
    block: (Element, Element, Element) -> T,
): T? =
    acceptAllOfOrNull(name1, name2, name3, variations = variations) { list ->
        val (elem1, elem2, elem3) = list
        block(elem1, elem2, elem3)
    }

/**
 * Visits the elements with the provided [name1], [name2], and [name3]. If [variations] is true, variations of the
 * names are also accepted. If at least one of the elements is missing, an [IllegalArgumentException] is thrown with
 * [message].
 */
fun <T> Visitor.accept(
    name1: String,
    name2: String,
    name3: String,
    message: String = "Missing at least one of the required elements: $name1, $name2, $name3",
    variations: Boolean = false,
    block: (Element, Element, Element) -> T,
): T =
    acceptAllOfOrThrow(name1, name2, name3, variations = variations, message = message) { (elem1, elem2, elem3) ->
        block(elem1, elem2, elem3)
    }

/**
 * Visits the elements with the provided [names1], [names2], and [names3], each one treated as alternative names of
 * each element. If [variations] is true, variations of the names are also accepted. Returns the result of [block] if
 * all elements are present, otherwise null.
 */
fun <T> Visitor.acceptAnyOfOrNull(
    names1: List<String>,
    names2: List<String>,
    names3: List<String>,
    variations: Boolean = false,
    block: (Element, Element, Element) -> T,
): T? =
    acceptAllOfOrNull(names1, names2, names3, variations = variations) { list ->
        val (elem1, elem2, elem3) = list
        block(elem1, elem2, elem3)
    }

/**
 * Visits the elements with the provided [names1], [names2], and [names3], each one treated as alternative names of
 * each element. If [variations] is true, variations of the names are also accepted. If at least one of the elements
 * is missing, an [IllegalArgumentException] is thrown with [message].
 */
fun <T> Visitor.acceptAnyOfOrThrow(
    names1: List<String>,
    names2: List<String>,
    names3: List<String>,
    message: String =
        "Missing at least one of the required elements: ${names1.joinToString()}, " +
            "${names2.joinToString()}, ${names3.joinToString()}",
    variations: Boolean = false,
    block: (Element, Element, Element) -> T,
): T =
    acceptAllOfOrThrow(
        names1,
        names2,
        names3,
        message = message,
        variations = variations,
    ) { (elem1, elem2, elem3) ->
        block(elem1, elem2, elem3)
    }

/**
 * Visits the elements with the provided [name1], [name2], [name3], and [name4]. If [variations] is true, variations
 * of the names are also accepted. Returns the result of [block] if all elements are present, otherwise null.
 */
fun <T> Visitor.acceptOrNull(
    name1: String,
    name2: String,
    name3: String,
    name4: String,
    variations: Boolean = false,
    block: (Element, Element, Element, Element) -> T,
): T? =
    acceptAllOfOrNull(name1, name2, name3, name4, variations = variations) { list ->
        val (elem1, elem2, elem3, elem4) = list
        block(elem1, elem2, elem3, elem4)
    }

/**
 * Visits the elements with the provided [name1], [name2], [name3], and [name4]. If [variations] is true, variations
 * of the names are also accepted. If at least one of the elements is missing, an [IllegalArgumentException] is
 * thrown with [message].
 */
fun <T> Visitor.accept(
    name1: String,
    name2: String,
    name3: String,
    name4: String,
    message: String = "Missing at least one of the required elements: $name1, $name2, $name3, $name4",
    variations: Boolean = false,
    block: (Element, Element, Element, Element) -> T,
): T =
    acceptAllOfOrThrow(
        name1,
        name2,
        name3,
        name4,
        message = message,
        variations = variations,
    ) { (elem1, elem2, elem3, elem4) ->
        block(elem1, elem2, elem3, elem4)
    }

/**
 * Visits the elements with the provided [names1], [names2], [names3], and [names4], each one treated as alternative
 * names of each element. If [variations] is true, variations of the names are also accepted. Returns the result of
 * [block] if all elements are present, otherwise null.
 */
fun <T> Visitor.acceptAnyOfOrNull(
    names1: List<String>,
    names2: List<String>,
    names3: List<String>,
    names4: List<String>,
    variations: Boolean = false,
    block: (Element, Element, Element, Element) -> T,
): T? =
    acceptAllOfOrNull(names1, names2, names3, names4, variations = variations) { list ->
        val (elem1, elem2, elem3, elem4) = list
        block(elem1, elem2, elem3, elem4)
    }

/**
 * Visits the elements with the provided [names1], [names2], [names3], and [names4], each one treated as alternative
 * names of each element. If [variations] is true, variations of the names are also accepted. If at least one of the
 * elements is missing, an [IllegalArgumentException] is thrown with [message].
 */
fun <T> Visitor.acceptAnyOfOrThrow(
    names1: List<String>,
    names2: List<String>,
    names3: List<String>,
    names4: List<String>,
    message: String =
        "Missing at least one of the required elements: ${names1.joinToString()}, " +
            "${names2.joinToString()}, ${names3.joinToString()}, ${names4.joinToString()}",
    variations: Boolean = false,
    block: (Element, Element, Element, Element) -> T,
): T =
    acceptAllOfOrThrow(
        names1,
        names2,
        names3,
        names4,
        message = message,
        variations = variations,
    ) { (elem1, elem2, elem3, elem4) ->
        block(elem1, elem2, elem3, elem4)
    }
